### ISSUE TITLE
make the prefix be configurable

### ISSUE THREAD

**Issue by yorkie** [nswbmw/config-lite#1]
@nswbmw hey i have met with a problem in using config with loopback's built-in config files. if this library is able to config the prefix, that's really awesome feature to integrate with other config directory like loopback.

The recommend argument way are:
- environment variable
- add a init function to config?

/cc @nswbmw

**Comment by nswbmw** [comment]
You means https://github.com/nswbmw/config-lite/blob/master/index.js#L6 ?

**Comment by yorkie** [comment]
Wow~ Muhammad, you are so smart. but could you support this style: `CONFIG_DIR`, actually few guys would write environment variables in CamelCase.
