### ISSUE TITLE
请问一下config-lite第二版和第一版相比更好的地方

### ISSUE THREAD

**Issue by jtsang4** [nswbmw/config-lite#6]
会有这种困惑是因为第一版直接require就可以使用配置信息了，但是第二版在不同的文件夹下还需要指定不同的路径信息才能获取到配置信息。

既然都要指定配置文件路径的话为什么不直接require那个路径下的指定配置文件呢，既然都要指定路径，config-lite不就没有让配置信息的读取变得更加方便了吗。

**Comment by nswbmw** [comment]
你去看下源码实现，config-lite 通过 resolve 模块可以实现冒泡查找，指定 __dirname 是从这个目录开始往上查找。第一版实现上其实有 bug

**Comment by jtsang4** [comment]
谢谢指点！
